name: vk-oc-rag-events
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  - pip
  - pip:
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-core==0.3.68
      - langchain-mistralai==0.2.11
      - mistralai==1.8.1

      - faiss-cpu==1.11.0
      - sentence-transformers==5.0.0

      - fastapi==0.116.1
      - uvicorn==0.35.0

      - pandas==2.3.1
      - numpy==2.3.1
      - pyarrow==21.0.0

      - python-dotenv==1.1.1
      - requests==2.32.4

      - ragas==0.3.0
      - datasets==4.0.0

      - pytest==8.4.1
      - pytest-cov==6.2.1
      - httpx==0.28.1

      - pydantic==2.11.7
      - tqdm==4.67.1

      - scikit-learn==1.7.0
      - matplotlib==3.10.3

      - jupyterlab==4.4.4
